package org.kcc.wordsets;

import org.kcc.CompletionItem;

public class JavaKeywords {

    public static final CompletionItem[] JAVA_KEYWORDS = {
           new CompletionItem("abstract"),
           new CompletionItem("assert"),
           new CompletionItem("boolean"),
           new CompletionItem("break"),
           new CompletionItem("byte"),
           new CompletionItem("case"),
           new CompletionItem("catch"),
           new CompletionItem("char"),
           new CompletionItem("class"),
           new CompletionItem("const"),
           new CompletionItem("continue"),
           new CompletionItem("default"),
           new CompletionItem("do"),
           new CompletionItem("double"),
           new CompletionItem("else"),
           new CompletionItem("enum"),
           new CompletionItem("extends"),
           new CompletionItem("final"),
           new CompletionItem("finally"),
           new CompletionItem("float"),
           new CompletionItem("for"),
           new CompletionItem("goto"),
           new CompletionItem("if"),
           new CompletionItem("implements"),
           new CompletionItem("import"),
           new CompletionItem("instanceof"),
           new CompletionItem("int"),
           new CompletionItem("interface"),
           new CompletionItem("long"),
           new CompletionItem("native"),
           new CompletionItem("new"),
           new CompletionItem("package"),
           new CompletionItem("private"),
           new CompletionItem("protected"),
           new CompletionItem("public"),
           new CompletionItem("return"),
           new CompletionItem("short"),
           new CompletionItem("static"),
           new CompletionItem("super"),
           new CompletionItem("switch"),
           new CompletionItem("synchronized"),
           new CompletionItem("this"),
           new CompletionItem("throw"),
           new CompletionItem("throws"),
           new CompletionItem("transient"),
           new CompletionItem("try"),
           new CompletionItem("void"),
           new CompletionItem("volatile"),
           new CompletionItem("while"),
           new CompletionItem("exports"),
           new CompletionItem("module"),
           new CompletionItem("non-sealed"),
           new CompletionItem("open"),
           new CompletionItem("opens"),
           new CompletionItem("permits"),
           new CompletionItem("provides"),
           new CompletionItem("record"),
           new CompletionItem("requires"),
           new CompletionItem("sealed"),
           new CompletionItem("to"),
           new CompletionItem("transitive"),
           new CompletionItem("uses"),
           new CompletionItem("var"),
           new CompletionItem("with"),
           new CompletionItem("yield"),
           new CompletionItem("true"),
           new CompletionItem("false"),
           new CompletionItem("null")
    };
}
